# Generated by Django 3.2.7 on 2021-11-09 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('estado_socio', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=15)),
                ('categoria', models.CharField(choices=[('Principienate', 'Socio Principiante'), ('Intermedio', 'Socio Intermedio'), ('Avanzado', 'Socio Avanzado')], max_length=25)),
                ('distrito', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=50)),
                ('direccion', models.CharField(max_length=40)),
                ('celular', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treunion', models.CharField(choices=[('Asambea', 'ASAMBLEA'), ('Padron', 'PADRON'), ('Faena', 'FAENA')], max_length=20)),
                ('descripción', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='completo.socio')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
    ]
