# Generated by Django 3.2.7 on 2021-11-10 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('completo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
